[build]
   base = "/"
   command = "echo 'no build command is needed'"

[[redirects]]
   from = "/test"
   to = "google.com"
   status = 301
   force = true

[[redirects]]
   # Redirect the default Netlify domain version of my apps URL to show/use my custom domain name version
   from = "https://gfl-one.netlify.com/*"
   to = "https://www.gflujan.com/:splat"
   status = 301
   force = true

